sudo: required
language: python

# Travis-CI currently only supports historical Ubuntu 14.04 containers:
# https://github.com/travis-ci/travis-ci/issues/5821
# keep-on-giffing requires a more modern ffmpeg/avconv, thus we're forced to use Docker instead.
services:
  - docker

env:
  - PYTHON_TAG=3.7-slim-stretch APT_PKG=ffmpeg
  - PYTHON_TAG=3.6-slim-stretch APT_PKG=ffmpeg
#  - PYTHON_TAG=3.5-slim-jessie APT_PKG=avconv-tools   # TODO FIXME
#  - PYTHON_TAG=3.4-slim-jessie APT_PKG=avconv-tools   # TODO FIXME
script:
  - docker build . --build-arg=PYTHON_TAG=$PYTHON_TAG --build-arg=APT_PKG=$APT_PKG

# TOOO: Cache wheelhouse etc as Docker volumes?
